version: '3'

services:
  vaultwarden:
    restart: unless-stopped
    container_name: vaultwarden
    image: vaultwarden/server:1.30.1-alpine
    volumes:
      - ./data/:/data/
    networks:
      - proxy
    ports:
      - 8062:80
    environment:
      - TZ=Europe/Copenhagen
      - LOGIN_RATELIMIT_MAX_BURST=10
      - LOGIN_RATELIMIT_SECONDS=60
      - DOMAIN=https://vaultwarden.wraaath.com
      - INVITATIONS_ALLOWED=true
      - ADMIN_TOKEN=${ADMIN_TOKEN}
      - EMERGENCY_ACCESS_ALLOWED=true
      - SENDS_ALLOWED=true
      - WEB_VAULT_ENABLED=true
    labels:
        - traefik.enable=true
        - traefik.docker.network=proxy
        - traefik.http.middlewares.redirect-https.redirectScheme.scheme=https
        - traefik.http.middlewares.redirect-https.redirectScheme.permanent=true
        - traefik.http.routers.vaultwarden-https.rule=Host(`vaultwarden.wraaath.com`)
        - traefik.http.routers.vaultwarden-https.entrypoints=https
        - traefik.http.routers.vaultwarden-https.tls=true
        - traefik.http.routers.vaultwarden-https.service=vaultwarden
        - traefik.http.routers.vaultwarden-http.rule=Host(`vaultwarden.wraaath.com`)
        - traefik.http.routers.vaultwarden-http.entrypoints=http
        - traefik.http.routers.vaultwarden-http.middlewares=redirect-https
        - traefik.http.routers.vaultwarden-http.service=vaultwarden
        - traefik.http.services.vaultwarden.loadbalancer.server.port=80
networks:
  proxy:
    external: true
