---
###############################################################
#                         Users Database                      #
###############################################################

# This file can be used if you do not have an LDAP set up.

# List of users
users:
  wraaath:
    displayname: "Mads"
    password: <argon2_hashed_pass>
    email: mads@wraaath.com
    groups:
      - admins
      - dev
...
