---
###############################################################
#                         Users Database                      #
###############################################################

# This file can be used if you do not have an LDAP set up.

# List of users
users:
  wraaath:
    displayname: "Mads"
    # Password is Authelia
    password: ${USER_PASS}
    email: mads@wraaath.com
    groups:
      - admins
      - dev
...
